### ISSUE TITLE
QA: Multi Comment Design

### ISSUE THREAD

**Issue by devpanther** [one-two-test/one#12]
Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.

**Comment by BitCognit** [comment]
Rest write

**Comment by BitCognit** [comment]
Test write

**Comment by BitCognit** [comment]
```coffeescript
Code block
print("Hello") ;
``` 

![social-davatar](https://github.com/one-two-test/one/assets/42383942/04d0cca0-069a-40e0-a575-a380523f5097)

**Comment by devpanther** [comment]
Here

**Comment by devpanther** [comment]
<details>
      <summary>
        <b>
          <h3>
            <a href="https://pay.ubq.fi?claim=eyJwZXJtaXQiOnsicGVybWl0dGVkIjp7InRva2VuIjoiMHhlOTFEMTUzRTBiNDE1MThBMkNlOERkM0Q3OTQ0RmE4NjM0NjNhOTdkIiwiYW1vdW50IjoiMTgwMDAwMDAwMDAwMDAwMDAwMCJ9LCJub25jZSI6IjEwMDg4OTg2NTIzNzM0MTAyMzA2Njg5NTk1MTE2MTA4OTQ1ODM2MzY4NTg0NTYyMzI5NjUxNDg2MzMzMTQ4MDY4Njg0MTMyNDUwNjQ1MiIsImRlYWRsaW5lIjoiMTE1NzkyMDg5MjM3MzE2MTk1NDIzNTcwOTg1MDA4Njg3OTA3ODUzMjY5OTg0NjY1NjQwNTY0MDM5NDU3NTg0MDA3OTEzMTI5NjM5OTM1In0sInRyYW5zZmVyRGV0YWlscyI6eyJ0byI6IjB4NzFDNzY1NkVDN2FiODhiMDk4ZGVmQjc1MUI3NDAxQjVmNmQ4OTc2RiIsInJlcXVlc3RlZEFtb3VudCI6IjE4MDAwMDAwMDAwMDAwMDAwMDAifSwib3duZXIiOiIweDk4MzhEOUQ2MmE0Nzk3MUQ1RTE3QzgyNDIzNUI1NjNjMTg2QjJDRDQiLCJzaWduYXR1cmUiOiIweDFiODEyMDlmZTEyZGZhY2U3NjAxNzBiZGMzMmM5M2JiOTBhMzc0YTc4ZjI3OGIzZDIxMzNiOWY5ZGZkOTQ4MGYxOWIxNDM5OGE4YTYzMDM2M2RkMzkwNjFjYTQxNDEwMjYzMDNhYjgzZjMzNjdkZDc3MWNjOTM3NDBhNDg4YWE5MWMifQ==&network=100">[ 1.8 WXDAI ]</a>
          </h3>
          <h6>&nbsp;@BitCognit</h6>
        </b>
      </summary>
      <code>
        <table>
          <tbody>
        <tr>
          <td>Issue</td>
          <td>Assignee</td>
          <td>1.3</td>
        </tr>
          </tbody>
        </table>
      </code>
    </details>
    <details>
      <summary>
        <b>
          <h3>
            <a href="https://pay.ubq.fi?claim=eyJwZXJtaXQiOnsicGVybWl0dGVkIjp7InRva2VuIjoiMHhlOTFEMTUzRTBiNDE1MThBMkNlOERkM0Q3OTQ0RmE4NjM0NjNhOTdkIiwiYW1vdW50IjoiMzAwMDAwMDAwMDAwMDAwMDAwMDAwIn0sIm5vbmNlIjoiMTQ0MjU0NzE2MTg1NzAxOTQyNTM4NzA0OTkwMDUxMzk4OTgwNDM0NDMyMjE4NzU5OTc5ODczMzkwMjMzODc0NjQ1MjI2NDA2NzEyMCIsImRlYWRsaW5lIjoiMTE1NzkyMDg5MjM3MzE2MTk1NDIzNTcwOTg1MDA4Njg3OTA3ODUzMjY5OTg0NjY1NjQwNTY0MDM5NDU3NTg0MDA3OTEzMTI5NjM5OTM1In0sInRyYW5zZmVyRGV0YWlscyI6eyJ0byI6IjB4YTgyZUVGMzY4MjFCMzVCN0FlRkI3MkRCQWVhYjZhMzFhNTgxNkY4MiIsInJlcXVlc3RlZEFtb3VudCI6IjMwMDAwMDAwMDAwMDAwMDAwMDAwMCJ9LCJvd25lciI6IjB4OTgzOEQ5RDYyYTQ3OTcxRDVFMTdDODI0MjM1QjU2M2MxODZCMkNENCIsInNpZ25hdHVyZSI6IjB4MmIyM2RkMDYwZmUxOTc3MmNhZGUyZjdhMTY0OGEzMGMwN2QwNWZhYTcyNGQ4NWNkYmU4ZTdkNDNiZDI5ODYxYzNmODA2NjFkMmNiOGFjMTc2OGE2YzkwMWU2ZGU5MDRiNmYzZWM2OGM0N2Y2MDZkZTUwYmQ3YzNmYWMzMWZlNTExYyJ9&network=100">[ 300 WXDAI ]</a>
          </h3>
          <h6>&nbsp;@devpanther</h6>
        </b>
      </summary>
      <code>
        <table>
          <tbody>
        <tr>
          <td>Issue</td>
          <td>Assignee</td>
          <td>300</td>
        </tr>
          </tbody>
        </table>
      </code>
    </details>
