### ISSUE TITLE
QA for Nested Incentives

### ISSUE THREAD

**Issue by devpanther** [one-two-test/one#3]
I am going to test this branch here, `/start` command will be overridden to display the repo config (just for the test)

**Comment by devpanther** [comment]
Org Config - https://github.com/one-two-test/ubiquibot-config/blob/main/.github/ubiquibot-config.yml
Repo Config - https://github.com/one-two-test/one/blob/main/.github/ubiquibot-config.yml

`code` is present in both Repo and Org - Repo was prioritized, thus `code: 20` not `code: 10`
`a` is absent in Repo Config but was merged in from Org Config
`li` is absent in Org Config, so it used the Repo Config

**Comment by BitCognit** [comment]
Tesst

**Comment by BitCognit** [comment]
Hhjjjjk

**Comment by BitCognit** [comment]
Hhhfsdrrrty
