### ISSUE TITLE
QA for different nonce on incentivize

### ISSUE THREAD

**Issue by devpanther** [one-two-test/one#4]
Users are encountering a persistent issue when attempting to submit the online registration form. Upon clicking the 'Submit' button, instead of the expected confirmation message, they are being presented with a '404 - Page Not Found' error page. This issue has been reported consistently by multiple users over the past two days.

The registration form is a critical component of our platform, and its proper functioning is essential for user engagement and business success. This unexpected error is causing confusion and frustration among users who are actively trying to sign up for our services.

Initial investigation suggests that the issue might be related to incorrect routing or a broken link within the form submission process. However, no recent changes have been made to the form's codebase, and it has been functioning correctly prior to this incident.

To address this issue, the development team needs to conduct a comprehensive review of the form's code to identify any potential bugs or misconfigurations that could lead to the '404' error. It's also important to review the server logs to determine if there are any unusual patterns or error messages that might shed light on the root cause.

**Comment by devpanther** [comment]
Oh, yeah.. I can do this

**Comment by devpanther** [comment]
Okay, here we go.. i don't know how to go about this issue

**Comment by devpanther** [comment]
```js
const permitTransferFromData: PermitTransferFrom = {
    permitted: {
      // token we are permitting to be transferred
      token: paymentToken,
      // amount we are permitting to be transferred
      amount: ethers.utils.parseUnits(amountInEth.toString(), 18),
    },
    // who can transfer the tokens
    spender: spender,
    nonce: BigNumber.from(keccak256(toUtf8Bytes(identifier + userId + type))),
    // signature deadline
    deadline: MaxUint256,
  };
```

**Comment by BitCognit** [comment]
I can help you with it, what do you need help with

**Comment by BitCognit** [comment]
Change the permit to pormit, it should work

```js
const permitTransferFromData: PermitTransferFrom = {
    permitted: {
      // token we are permitting to be transferred
      token: paymentToken,
      // amount we are permitting to be transferred
      amount: ethers.utils.parseUnits(amountInEth.toString(), 18),
    },
    // who can transfer the tokens
    spender: spender,
    nonce: BigNumber.from(keccak256(toUtf8Bytes(identifier + userId + type))),
    // signature deadline
    deadline: MaxUint256,
  };
```

**Comment by devpanther** [comment]
I've attached a fix

**Comment by BitCognit** [comment]
Your fix is trash, come on

**Comment by BitCognit** [comment]
> Your fix is trash, come on

![images (32)](https://github.com/one-two-test/one/assets/133535609/ebbbc2e1-d0b6-4446-8a7e-5402cbfbfd67)

**Comment by BitCognit** [comment]
Oh, yea.. You debugging

**Comment by BitCognit** [comment]
Okay, you have to turn on incentive mode

**Comment by BitCognit** [comment]
Error: Error is probably from not having permits table in db
