### ISSUE TITLE
QA for different nonce on incentivize 

### ISSUE THREAD

**Issue by devpanther** [one-two-test/one#6]
Users are encountering a persistent issue when attempting to submit the online registration form. Upon clicking the 'Submit' button, instead of the expected confirmation message, they are being presented with a '404 - Page Not Found' error page. This issue has been reported consistently by multiple users over the past two days.

The registration form is a critical component of our platform, and its proper functioning is essential for user engagement and business success. This unexpected error is causing confusion and frustration among users who are actively trying to sign up for our services.

Initial investigation suggests that the issue might be related to incorrect routing or a broken link within the form submission process. However, no recent changes have been made to the form's codebase, and it has been functioning correctly prior to this incident.

To address this issue, the development team needs to conduct a comprehensive review of the form's code to identify any potential bugs or misconfigurations that could lead to the '404' error. It's also important to review the server logs to determine if there are any unusual patterns or error messages that might shed light on the root cause.

**Comment by devpanther** [comment]
Hello, i think i can do this

**Comment by devpanther** [comment]
Even though i just created the task myself

**Comment by BitCognit** [comment]
No, you can't 🤔

**Comment by devpanther** [comment]
I just linked a PR lol

**Comment by BitCognit** [comment]
The PR is trash, it's never gonna get approved

**Comment by BitCognit** [comment]
![images (32)](https://github.com/one-two-test/one/assets/133535609/e67ecfbd-52a6-4878-8537-60615b610776)

Grey curtain

**Comment by devpanther** [comment]
Don't care about your curtain

I am having issues here

```js
// Join creator earnings to assignee if its same user, or handle differently
  if (incentivizedCreator && incentivizedCreator.account && incentivizedCreator.comment && incentivizedCreator.user !== assignee.login) {
    const { payoutUrl } = await generatePermit2Signature(incentivizedCreator.account, incentivizedCreator.amountInETH!, incentivizedCreator.node_id!, incentivizedCreator.userId, "ISSUE_CREATOR");
    creatorComment = `${incentivizedCreator.comment}### [ **${incentivizedCreator.user}: [ CLAIM ${incentivizedCreator.amountInETH} ${tokenSymbol.toUpperCase()} ]** ](${payoutUrl})\n`;

    logger.info(`Permit url generated for creator. reward: ${payoutUrl}`);
    await addCommentToIssue(creatorComment, issue.number);
  }

  if(incentivizedComment) {
    await addCommentToIssue(incentivizedComment, issue.number);
  }
```

**Comment by BitCognit** [comment]
Change `issue.number` to `issue.null`

```js
// Join creator earnings to assignee if its same user, or handle differently
  if (incentivizedCreator && incentivizedCreator.account && incentivizedCreator.comment && incentivizedCreator.user !== assignee.login) {
    const { payoutUrl } = await generatePermit2Signature(incentivizedCreator.account, incentivizedCreator.amountInETH!, incentivizedCreator.node_id!, incentivizedCreator.userId, "ISSUE_CREATOR");
    creatorComment = `${incentivizedCreator.comment}### [ **${incentivizedCreator.user}: [ CLAIM ${incentivizedCreator.amountInETH} ${tokenSymbol.toUpperCase()} ]** ](${payoutUrl})\n`;

    logger.info(`Permit url generated for creator. reward: ${payoutUrl}`);
    await addCommentToIssue(creatorComment, issue.number);
  }

  if(incentivizedComment) {
    await addCommentToIssue(incentivizedComment, null);
  }
```

**Comment by devpanther** [comment]
Null?, wdym issue.null

**Comment by BitCognit** [comment]
You so dumb, the code says it all

**Comment by devpanther** [comment]
You know what, i am done here.. let's link this up

**Comment by BitCognit** [comment]
Lol, you're so dumb.. You didn't even assign yourself
