### ISSUE TITLE
QA: Consolidate Rewards Test Code

### ISSUE THREAD

**Issue by devpanther** [one-two-test/one#7]
Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.

**Comment by BitCognit** [comment]
You cant do this

**Comment by BitCognit** [comment]
I have to comment

**Comment by BitCognit** [comment]
Lorem ipsum

```js
console.log(gg)
```

**Comment by devpanther** [comment]
Testing comment

**Comment by devpanther** [comment]
Comment commenter

**Comment by devpanther** [comment]
See if it works

**Comment by BitCognit** [comment]
It can't

**Comment by BitCognit** [comment]
It cannot can't
