### ISSUE TITLE
QA: Consolidate Rewards Test 1

### ISSUE THREAD

**Issue by devpanther** [one-two-test/one#8]
Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.

**Comment by devpanther** [comment]
What am i saying

**Comment by BitCognit** [comment]
What should you write

**Comment by devpanther** [comment]
I don't know, i am having problems

**Comment by BitCognit** [comment]
Here

```js
console.log("Hello") ;
```

**Comment by BitCognit** [comment]
Perhaps that'd work

**Comment by devpanther** [comment]
I don't think so, imma end this

**Comment by devpanther** [comment]
Oops
