### ISSUE TITLE
QA: Consolidate Reward Test 2

### ISSUE THREAD

**Issue by BitCognit** [one-two-test/one#9]
Because there is no way to change a block, the only trust needed is at the point where a user or program enters data. This aspect reduces the need for trusted third parties, which are usually auditors or other humans that add costs and make mistakes.

Since Bitcoin's introduction in 2009, blockchain uses have exploded via the creation of various cryptocurrencies, decentralized finance (DeFi) applications, non-fungible tokens (NFTs), and smart contracts.

You might be familiar with spreadsheets or databases. A blockchain is somewhat similar because it is a database where information is entered and stored. But the key difference between a traditional database or spreadsheet and a blockchain is how the data is structured and accessed.

**Comment by devpanther** [comment]
I can get this done

**Comment by BitCognit** [comment]
You should not get assigned

**Comment by BitCognit** [comment]
You cant pull it off

**Comment by BitCognit** [comment]
You cant write

**Comment by devpanther** [comment]
Of course i can, would i get the reward?

**Comment by devpanther** [comment]
I bet i would

**Comment by BitCognit** [comment]
No, you wouldn't

**Comment by BitCognit** [comment]
Nooooo
